---
title: "p8105_hw5_yg2625"
author: "Yue Gu"
date: "November 7, 2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Library
```{r, message = F}
library(tidyverse)
library(rvest)
library(purrr)
```

## Problem 1
### Create dataframe containing all file names
```{r}
file_df = tibble(
  list.files(path = "./data", pattern = "*.csv")
  )
names(file_df)[1] = "file_name"

file_df
```

### Iterate over file names and read in data
```{r, message = F}
arm_df = 
  file_df %>% 
  mutate(path = str_c("./data/", file_name)) %>% 
  mutate(data = map(path, read_csv)) %>% 
  unnest()

arm_df

```

### Tidy the resulting data
```{r}
arm_tidy =
  arm_df %>% 
  select(-path) %>% 
  mutate(file_name = str_replace(file_name, ".csv", "")) %>% 
  separate(file_name, into = c("arm", "subject_id"), sep = "_") %>% 
  gather(key = week, value = obs, week_1:week_8) %>% 
  mutate(week = str_replace(week, "week_", ""))

head(arm_tidy, 10)  
```

### Make a spaghetti plot
```{r}
arm_tidy %>%
  ggplot(aes(x = week, y = obs, group = subject_id, color = subject_id)) +
  geom_point(alpha = .5) +
  geom_line() +
  facet_grid(~arm) +
  theme(legend.position = "bottom") +
  labs(title = "Spaghetti plot showing observations on each subject over time",
       x = "Week",
       y = "Observations")
```
### By



